name: vars test

on:
  workflow_dispatch:
  push:

env:
  # Setting an environment variable with the value of a configuration variable
  _: ${{ vars._ }}

jobs:
  display-variables:
    name: ${{ vars.JOB_NAME }}
    # You can use configuration variables with the `vars` context for dynamic jobs
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    steps:
      - name: Use variables
        run: |
          echo "repository variable : ${{ vars.REPOSITORY_VAR }}"
          echo "organization variable : ${{ vars.ORGANIZATION_VAR }}"
          echo "overridden variable : ${{ vars.OVERRIDE_VAR }}"
          echo "variable from shell environment : $env_var"

      - name: HELLO_WORLD_STEP
        if: ${{ vars.HELLO_WORLD_ENABLED == 'true' }}
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ vars.GREET_NAME }}
